### ISSUE TITLE
add command line parameters --available-[warning|notification]

### ISSUE THREAD

**Issue by justinotherguy** [section77/datenverbrauch#2]
Servus,
it would be very handy to get a notification or warning when the remaining volume is below certain values,
Any chance?
Thx! :)

**Comment by j-keck** [comment]
better to rename '--usage-xxx' to '--available-xx' - my fault. i'm on it.

**Comment by j-keck** [comment]
fixed in ea44d3fcca99a0ebfba013e28f7e61376fdf6012
